/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package group_7_online_amusement_park_reservation_system;


public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminMenu
     */
    public AdminMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addstaffBTN = new javax.swing.JButton();
        removestaffBTN = new javax.swing.JButton();
        banuserBTN = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();
        addadminBTN = new javax.swing.JButton();
        AddTicket = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN'S MENU");

        addstaffBTN.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        addstaffBTN.setForeground(new java.awt.Color(0, 102, 102));
        addstaffBTN.setText("Add Staff");
        addstaffBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstaffBTNActionPerformed(evt);
            }
        });

        removestaffBTN.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        removestaffBTN.setForeground(new java.awt.Color(0, 102, 102));
        removestaffBTN.setText("Remove Staff");
        removestaffBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removestaffBTNActionPerformed(evt);
            }
        });

        banuserBTN.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        banuserBTN.setForeground(new java.awt.Color(0, 102, 102));
        banuserBTN.setText("Ban User ");
        banuserBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banuserBTNActionPerformed(evt);
            }
        });

        backBTN.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        backBTN.setForeground(new java.awt.Color(0, 102, 102));
        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        addadminBTN.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        addadminBTN.setForeground(new java.awt.Color(0, 102, 102));
        addadminBTN.setText("Add Admin");
        addadminBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addadminBTNActionPerformed(evt);
            }
        });

        AddTicket.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AddTicket.setForeground(new java.awt.Color(0, 102, 102));
        AddTicket.setText("Add Ticket");
        AddTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTicketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBTN))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AddTicket, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addadminBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addComponent(addstaffBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removestaffBTN)
                            .addComponent(banuserBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addstaffBTN)
                    .addComponent(removestaffBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(banuserBTN)
                    .addComponent(addadminBTN))
                .addGap(56, 56, 56)
                .addComponent(AddTicket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(backBTN)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addstaffBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstaffBTNActionPerformed
        AddStaff f1=new AddStaff();
        f1.setVisible(true);
        this.dispose();
        f1.setLocationRelativeTo(null);
    }//GEN-LAST:event_addstaffBTNActionPerformed

    private void removestaffBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removestaffBTNActionPerformed
        RemoveStaff f2=new RemoveStaff();
        f2.setVisible(true);
        this.dispose();
        f2.setLocationRelativeTo(null);
    }//GEN-LAST:event_removestaffBTNActionPerformed

    private void banuserBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banuserBTNActionPerformed
        BanUser f3=new BanUser();
        f3.setVisible(true);
        this.dispose();
        f3.setLocationRelativeTo(null);
    }//GEN-LAST:event_banuserBTNActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        MainGUI main=new MainGUI();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBTNActionPerformed

    private void addadminBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addadminBTNActionPerformed
        CheckAccess f6= new CheckAccess();
        f6.setVisible(true);
        f6.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_addadminBTNActionPerformed

    private void AddTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTicketActionPerformed
TicketGUI t=new TicketGUI();
t.setVisible(true);
this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_AddTicketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTicket;
    private javax.swing.JButton addadminBTN;
    private javax.swing.JButton addstaffBTN;
    private javax.swing.JButton backBTN;
    private javax.swing.JButton banuserBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton removestaffBTN;
    // End of variables declaration//GEN-END:variables
}
