/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package group_7_online_amusement_park_reservation_system;

import com.sun.jdi.connect.spi.Connection;
import group_7_online_amusement_park_reservation_system.CashBackDecorator;
import group_7_online_amusement_park_reservation_system.Customer;
import group_7_online_amusement_park_reservation_system.DiscountDecorator;
import group_7_online_amusement_park_reservation_system.Payment;
import group_7_online_amusement_park_reservation_system.PaymentComponent;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author dell
 */
public class PaymentUI extends javax.swing.JFrame {

    /**
     * Creates new form PaymentUI
     */
    public PaymentUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CardNumberFeild = new javax.swing.JTextField();
        DateFeild = new javax.swing.JTextField();
        CVVFeild = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CashBackRadio = new javax.swing.JRadioButton();
        DiscountRadio = new javax.swing.JRadioButton();
        ProccessBttn = new javax.swing.JButton();
        CustomerIDFeild = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Payment");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Card Number");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EXP Date");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CVV");

        CardNumberFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardNumberFeildActionPerformed(evt);
            }
        });

        DateFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateFeildActionPerformed(evt);
            }
        });

        CVVFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CVVFeildActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Discount Type:");

        CashBackRadio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CashBackRadio.setForeground(new java.awt.Color(255, 255, 255));
        CashBackRadio.setText("Cash back");
        CashBackRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashBackRadioActionPerformed(evt);
            }
        });

        DiscountRadio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DiscountRadio.setForeground(new java.awt.Color(255, 255, 255));
        DiscountRadio.setText("Normal Discount");
        DiscountRadio.setToolTipText("");
        DiscountRadio.setName("Normal Discount "); // NOI18N
        DiscountRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscountRadioActionPerformed(evt);
            }
        });

        ProccessBttn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ProccessBttn.setText("process");
        ProccessBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProccessBttnActionPerformed(evt);
            }
        });

        CustomerIDFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerIDFeildActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Customer ID");

        Back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CardNumberFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustomerIDFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CVVFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DiscountRadio)
                            .addComponent(CashBackRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 252, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ProccessBttn)
                        .addGap(12, 12, 12))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(DateFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(CVVFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(CardNumberFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustomerIDFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DiscountRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CashBackRadio)))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProccessBttn)
                    .addComponent(Back))
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CardNumberFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardNumberFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CardNumberFeildActionPerformed

    private void CashBackRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashBackRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CashBackRadioActionPerformed

    private void DiscountRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscountRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiscountRadioActionPerformed

    private void ProccessBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProccessBttnActionPerformed

    String cardText = CardNumberFeild.getText().trim();
        String cvvText  = CVVFeild.getText().trim();
        String expDate  = DateFeild.getText().trim();
        String custID   = CustomerIDFeild.getText().trim();

        // 1) Validate inputs
        if (cardText.isEmpty() || cvvText.isEmpty() || expDate.isEmpty() || custID.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "All fields must be filled in.",
                "Error", JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        if (!cardText.matches("\\d{8}")) {
            JOptionPane.showMessageDialog(this,
                "Card number must be exactly 8 digits.",
                "Error", JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        if (!cvvText.matches("\\d{3}")) {
            JOptionPane.showMessageDialog(this,
                "CVV must be exactly 3 digits.",
                "Error", JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        if (!expDate.matches("(0[1-9]|1[0-2])/\\d{2}")) {
            JOptionPane.showMessageDialog(this,
                "Expiration date must be in MM/YY format.",
                "Error", JOptionPane.ERROR_MESSAGE
            );
            return;
        }

       
        java.sql.Connection conn = null;
        Statement stmt = null;
        try {
            conn = DB.getInstance().getConnection();
            stmt = conn.createStatement();

            // check if the customer id exists in the db
            java.sql.ResultSet rs = stmt.executeQuery(
                "SELECT * FROM Customer WHERE customerID = '" + custID + "'"
            );
            if (!rs.first()) {
                JOptionPane.showMessageDialog(this,
                    "Customer ID `" + custID + "` not found.",
                    "Error", JOptionPane.ERROR_MESSAGE
                );
                return;
            }


            // 5) dummy amounts 
            int amount  = 500;
            int balance = 600;
            int cardNum = Integer.parseInt(cardText);
            int cvv     = Integer.parseInt(cvvText);

            //  validate via controller
            PaymentController controller = new PaymentController();
            controller.CheckPaymentDetails(cardNum, cvv, expDate);
            controller.CheckBalance(amount, balance);

            // make payment object and apply decorator
            Payment p1 = new Payment( amount, "card",cardNum, cvv, expDate, balance, Integer.parseInt(custID));
            PaymentComponent payment = new Payment( amount, "card",cardNum, cvv, expDate, balance, Integer.parseInt(custID));
            if (DiscountRadio.isSelected()) {
                payment = new DiscountDecorator(payment, 50);
            } else if (CashBackRadio.isSelected()) {
                payment = new CashBackDecorator(payment, 50);
            }

            // 8) show message according to the radio button choice (decorator)
            String message = payment.getPaymentMessage();
            int confirm = JOptionPane.showConfirmDialog(
                this, message + "\nProceed?",
                "Confirm Payment", JOptionPane.YES_NO_OPTION
            );
            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }

            // 9) ensure funds are sufficient post‐decoration
            if (payment.getBalance() < payment.getAmount()) {
                JOptionPane.showMessageDialog(this,
                    "Insufficient funds after discount/cashback.",
                    "Error", JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            p1.saveToDatabase(payment);

            JOptionPane.showMessageDialog(this,
                "Payment saved successfully.",
                "Success", JOptionPane.INFORMATION_MESSAGE
            );

            
            CardNumberFeild.setText("");
            CVVFeild.setText("");
            DateFeild.setText("");
            CustomerIDFeild.setText("");
            DiscountRadio.setSelected(false);
            CashBackRadio.setSelected(false);
            
            OLDcustomer oc=new OLDcustomer();
            oc.setVisible(true);
            this.dispose();

        } catch (Exception e) {
            System.err.println("ERROR in processing payment: " + e);
            JOptionPane.showMessageDialog(this,
                "An unexpected error occurred:\n" + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE
            );
        } 
        
        
    }//GEN-LAST:event_ProccessBttnActionPerformed

    private void DateFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateFeildActionPerformed

    private void CVVFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CVVFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CVVFeildActionPerformed

    private void CustomerIDFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerIDFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerIDFeildActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
      OLDcustomer oc=new OLDcustomer();
      oc.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField CVVFeild;
    private javax.swing.JTextField CardNumberFeild;
    private javax.swing.JRadioButton CashBackRadio;
    private javax.swing.JTextField CustomerIDFeild;
    private javax.swing.JTextField DateFeild;
    private javax.swing.JRadioButton DiscountRadio;
    private javax.swing.JButton ProccessBttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
