package group_7_online_amusement_park_reservation_system;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ali Tamer
 */
import java.util.List;
import java.util.*;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.DriverManager;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
public class TicketGUI extends javax.swing.JFrame {

    /**
     * Creates new form Ticket
     */
    public TicketGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TicketGUI = new javax.swing.JLabel();
        TicketDate = new javax.swing.JLabel();
        Information = new javax.swing.JLabel();
        TicketID = new javax.swing.JLabel();
        TicketCategory = new javax.swing.JLabel();
        TicketID_txtField = new javax.swing.JTextField();
        TicketDate_txtField = new javax.swing.JTextField();
        TicketCategory_txtField = new javax.swing.JTextField();
        Back_To_Main_Menu_Button = new javax.swing.JButton();
        Submit_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        TicketGUI.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TicketGUI.setForeground(new java.awt.Color(255, 255, 255));
        TicketGUI.setText("Ticket GUI");

        TicketDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TicketDate.setForeground(new java.awt.Color(255, 255, 255));
        TicketDate.setText("Ticket Date");

        Information.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Information.setForeground(new java.awt.Color(255, 255, 255));
        Information.setText("Information");

        TicketID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TicketID.setForeground(new java.awt.Color(255, 255, 255));
        TicketID.setText("Ticket ID");

        TicketCategory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TicketCategory.setForeground(new java.awt.Color(255, 255, 255));
        TicketCategory.setText("Ticket Category");

        TicketID_txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketID_txtFieldActionPerformed(evt);
            }
        });

        TicketDate_txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketDate_txtFieldActionPerformed(evt);
            }
        });

        TicketCategory_txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketCategory_txtFieldActionPerformed(evt);
            }
        });

        Back_To_Main_Menu_Button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Back_To_Main_Menu_Button.setText("Back To Admin Menu ");
        Back_To_Main_Menu_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_To_Main_Menu_ButtonActionPerformed(evt);
            }
        });

        Submit_Button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Submit_Button.setText("Submit");
        Submit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TicketGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(Back_To_Main_Menu_Button))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(Submit_Button)))
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Information, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TicketID)
                            .addComponent(TicketDate, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TicketDate_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TicketID_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TicketCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TicketCategory_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(TicketGUI)
                .addGap(30, 30, 30)
                .addComponent(Information)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TicketID)
                    .addComponent(TicketID_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TicketDate)
                    .addComponent(TicketDate_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TicketCategory)
                    .addComponent(TicketCategory_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(Back_To_Main_Menu_Button)
                .addGap(18, 18, 18)
                .addComponent(Submit_Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TicketCategory_txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketCategory_txtFieldActionPerformed
        System.out.println("Ticket category entered: " + TicketCategory_txtField.getText());
    }//GEN-LAST:event_TicketCategory_txtFieldActionPerformed

    private void TicketID_txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketID_txtFieldActionPerformed
        System.out.println("Ticket ID entered: " + TicketID_txtField.getText());
    }//GEN-LAST:event_TicketID_txtFieldActionPerformed

    private void Back_To_Main_Menu_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_To_Main_Menu_ButtonActionPerformed
    AdminMenu main=new AdminMenu();
    main.show();
    dispose();
    }//GEN-LAST:event_Back_To_Main_Menu_ButtonActionPerformed

    private void Submit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_ButtonActionPerformed
      try {
        int ticketID = Integer.parseInt(TicketID_txtField.getText()); // Only if ticketID is entered manually
        String ticketDate = TicketDate_txtField.getText().trim();
        String ticketCategory = TicketCategory_txtField.getText().trim();

        // Validation
        if (ticketDate.isEmpty() || ticketCategory.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Connection conn = DB.getInstance().getConnection();

        // If ticketID is AUTO_INCREMENT in database, remove it from INSERT
        String sql = "INSERT INTO ticket (ticketID, ticketDate, themeName) VALUES (?, ?, ?)";
        PreparedStatement stmt = conn.prepareStatement(sql);

        stmt.setInt(1, ticketID);  // ❗Remove this line if ticketID is auto-increment
        stmt.setString(2, ticketDate); // Assuming it's saved as text; otherwise, parse date properly
        stmt.setString(3, ticketCategory);

        int inserted = stmt.executeUpdate();
        if (inserted > 0) {
            JOptionPane.showMessageDialog(this, "Ticket created successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Clear fields after success
            TicketID_txtField.setText("");
            TicketDate_txtField.setText("");
            TicketCategory_txtField.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Failed to create ticket.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_Submit_ButtonActionPerformed

    private void TicketDate_txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketDate_txtFieldActionPerformed
       System.out.println("Ticket date entered: " + TicketDate_txtField.getText());
    }//GEN-LAST:event_TicketDate_txtFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TicketGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_To_Main_Menu_Button;
    private javax.swing.JLabel Information;
    private javax.swing.JButton Submit_Button;
    private javax.swing.JLabel TicketCategory;
    private javax.swing.JTextField TicketCategory_txtField;
    private javax.swing.JLabel TicketDate;
    private javax.swing.JTextField TicketDate_txtField;
    private javax.swing.JLabel TicketGUI;
    private javax.swing.JLabel TicketID;
    private javax.swing.JTextField TicketID_txtField;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
